### ISSUE TITLE
Update pngjs dependency

### ISSUE THREAD

**Issue by popod** [soldair/node-qrcode#85] opened 2017-07-28 10:29 UTC
Please, could you update your package.json dependencies for pngjs from 2.3.1 to latest 3.2.0 ?

**Comment by vigreco** [comment] 2017-07-28 10:51
Hi @popod,
do you have a specific issue caused by version 2.3.1 of `pngjs`?

**Comment by popod** [comment] 2017-07-28 11:13
Not really with node-qrcode, but when I try to run unit tests with karma in my existing project, I've this warning (and it seems that this not appear with pngjs 3.2.0) :

```
$ npm run unit

> karma start test/unit/karma.conf.js

WARNING in ./app/node_modules/pngjs/lib/parser-sync.js
Module not found: Error: Can't resolve 'node-zlib-backport' in '/app/node_modules/pngjs/lib'
 @ ./app/node_modules/pngjs/lib/parser-sync.js 8:11-40
 @ ./app/node_modules/pngjs/lib/png-sync.js
 @ ./app/node_modules/pngjs/lib/png.js
 @ ./app/node_modules/qrcode/lib/renderer/png.js
 @ ./app/node_modules/qrcode/lib/server.js
 @ ./app/node_modules/qrcode/lib/index.js
 @ ./app/src/renderer/utils/generateInvoicesPdf.js
 @ ./app/src/renderer ^\.\/(?!main(\.js)?$)
 @ ./test/unit/index.js
```

**Comment by vigreco** [comment] 2017-07-28 12:04
@popod are you running this in a browser?
`pngjs` should not be included in the final bundle, it's only for node.
Can you provide a snippet to help me to reproduce the issue?

**Comment by popod** [comment] 2017-08-09 06:07
@vigreco no, I'm running this in an electron.js application (so this is not a problem with node). I use webpack and some others tools, so a snippet will be hard to provide..

**Comment by soldair** [comment] 2017-08-09 18:51
fwiw im ok with dropping support for node <4 if we push a new major. things are in really good shape and this kind of problem with pngjs is an emerging pattern

**Comment by vigreco** [comment] 2017-08-11 07:13
@soldair I'd like to drop old node versions too. Node 0.10 and 0.12 are not supported anymore since [last year](https://github.com/nodejs/LTS#lts-schedule1) and they often create annoying errors/warnings.
I can send a PR if you agree.

@popod till then, if it works for you, you can import `'qrcode/lib/browser'` in place of `'qrcode'` and use [browser API](https://github.com/soldair/node-qrcode#browser-api) like `toDataURL`. This should avoid errors due to pngjs.

**Comment by soldair** [comment] 2017-08-11 16:26
i agree :confetti_ball:

**Comment by stevgouws** [comment] 2017-10-24 13:01
I'm having the same issue with Electron. Thanks.

**Comment by vigreco** [comment] 2017-10-24 13:50
@stevgouws I'm working on it right now. Will be fixed soon.

**Comment by stevgouws** [comment] 2017-10-25 04:33
@vigreco Thanks so much.

**Comment by vigreco** [comment] 2017-11-08 10:14
node-qrcode now uses the latest version of pngjs.
Thanks everyone!

**Closed by vigreco** 2017-11-08 10:14 UTC
